import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'
import profilePic from '/public/wechat.jpg'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Deo Zhang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/letter-d.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Link href="/posts/page-test">page-test</Link>
          <Link href="/posts/first-post">first-post</Link>
          <a
            href="https://www.youtube.com/channel/UCjzTFhv2rbGA4PzijWwKC6w?sub_confirmation=1"
            rel="noopener noreferrer"
          >
            Youtube{' '}
          </a>
        </div>
        <div>
            <Image
                src={profilePic}
                alt="Picture of the author"
                width={340}
                height={470}
            />
        </div>

        <div className={styles.grid}>
          <a
            href="https://www.youtube.com/channel/UCjzTFhv2rbGA4PzijWwKC6w?sub_confirmation=1"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Youtube <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Welcome to my youtube channel.
            </p>
          </a>
          <a
            href="https://www.youtube.com/channel/UCjzTFhv2rbGA4PzijWwKC6w?sub_confirmation=1"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Youtube <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Welcome to my youtube channel.
            </p>
          </a>
          <a
            href="https://www.youtube.com/channel/UCjzTFhv2rbGA4PzijWwKC6w?sub_confirmation=1"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Youtube <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Welcome to my youtube channel.
            </p>
          </a>
          <a
            href="https://github.com/deozhang"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Github <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Welcome to my youtube channel.
            </p>
          </a>    
        </div>
      </main>
    </>
  )
}
